[project]
name = "sphinterp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=7.1.0",
    "healpy>=1.18.1",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "polars>=1.31.0",
]
