[project]
name = "sphinterp"
version = "1.0.0"
description = "Catalogue interpolation on the sphere with HEALPix"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "astropy>=6",
    "healpy>=1",
    "numpy>=2",
    "pandas>=2",
    "polars>=1.3",
]
